### ISSUE TITLE
Duplicated note created for each new annotation

### ISSUE THREAD

**Issue by graphit0** [ravenscroftj/joplin-hypothesis#4]
### Description
When adding an annotation the plugin creates 2 separate notes for it

### Steps
1. Create public annotation
2. Plugin: Reset last retrieval
3. Observe 2 separate notes appear

### Demonstration
https://user-images.githubusercontent.com/44114323/207061802-e96f938e-5046-4323-9cd9-85e19ea32777.mp4

### Expected result
For each annotation only a single note should be created

### Notes
- restart of Joplin didn't help
- once the duplicate is deleted manually, the plugin doesn't import it again :+1: 

### Environment
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-56-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3 CPU M 370 @ 2.40GHz
Memory: 7,6 GiB of RAM
Graphics Processor: AMD REDWOOD

- Joplin 2.8.8 (prod, linux)
- Joplin Hypothes.is  v0.1.0
- [Unofficial Hypothesis extension](https://github.com/diegodlh/unofficial-hypothesis-extension/issues) Version 1.470.0.2
- Firefox 107 (tar package)
- [Webpage used for testing](https://www.ontestautomation.com/the-four-pillars-of-object-oriented-programming-part-1-encapsulation/)

**Comment by ravenscroftj** [comment]
Thanks very much for contributing to the project by sharing this issue. I will have a look into it. I think it must be something to do with the method I am using to page through annotations in the hypothes.is API.

**Comment by ravenscroftj** [comment]
Should now be fixed as of commit [1bff894](https://github.com/ravenscroftj/joplin-hypothesis/commit/1bff894d3d4df75327b921c092fe23b2665b13e4) and release v0.1.1 which should propagate to Joplin's plugin store in the next few minutes.

Basically there were 2 issues that were co-mingling. Firstly the timestamps on the notes coming back from hypothesis are more precise than the timestamps stored in Joplin so we were ending up with an issue where the most recent note was always a few milliseconds newer than the "last fetch date" causing it to show up multiple times.

Secondly an event handler listening for changes to settings was triggering a re-run of the plugin every time the last fetch date was stored (since we store this in settings).

Let me know if you have any more problems with this issue once you have v0.1.1 installed
